### ISSUE TITLE
Longer cables and cable management arms?

### ISSUE THREAD

**Issue by yohell** [NBISweden/aida-data-hub#696]
Should we consider getting longer cables and installing cable management arms on the machines that have top-of-chassis disk slots? 

Until we do so, we may be required to take servers offline if we ever need to access those slots. 

On the other hand if we ever need to access that slot, it's probably because the disk is broken and the server is useless anyway, so it doesn't matter if it's taken offline?

**Comment by pontus** [comment]
Primarily this can be up to the ones who most often visit the computer room, but I opted for not using cable arms because shutting down the node should always be possible without causing service interruptions and cable arms typically makes things more difficult for everything except pulling out the node and opening it.

Specifically, it makes cable access very difficult, including seeing lights. It also adds a significant step to mounting and makes mount take longer. Typically it also impedes airflow.
