### ISSUE TITLE
What is the read performance of the archive?

### ISSUE THREAD

**Issue by yohell** [NBISweden/aida-data-hub#71]
How long does it take to read through all the stored data?

This can for example be done by creating a job that reads through some data in the repository, counts how much is read and the time it took and throws away the output.

- [x] What is the absolute max byte/sec performance of BP storage

Read performance of the archive data from safespring instance is 154036772.727 byte/sec

```
596430384 of 596430384   100% in    3s   152.70 MB/s  done
real	0m3.872s
user	0m1.700s
sys	0m0.554s
```

**Comment by pontus** [comment]
Could we get some larger runs so we are more confident that we're seeing sustained performance rather than getting a peak at the start and then dropping? Getting several objects would be okay and then calculating across it all, ignoring any housekeeping time (so just total fetched size/walltime). I'd also recommend doing repeated runs to see if we get the same (but objects will very likely be cached on the machine serving them so one might want to rotate).

If one wants to do extra, it could also be interesting to collect e.g. 8 Gbytes of large objects and see what one gets for those and compare it to 8 Gbytes of small objects (with whatever cutoff one decides on, 1 or 5 Mbytes?).

Also worth noting is that unless one makes sure writes don't go to disk, they may both be a limiting factor as well as interfere with the bandwidth used for download, so one should at least do a test with e.g. `dd if=/dev/null of=largefile bs=16M count=1024` (or whatever is suitable based on the available space) and see if that's in the same range.

(I don't know how safe spring has set up their networking, so disk usage could be done on the same interface as machine networking, or not.)
